app_name = "amb_w_tds"
app_version = "9.2.0"
app_title = "AMB W TDS"
app_publisher = "Your Company"
app_description = "AMB With TDS"
app_email = "support@yourcompany.com"
app_license = "MIT"

# ========================================
#  MODULE LOAD + PATCH PREPARATION
# ========================================

# register custom DocTypes for override / extension
doctype_class = {
    "Batch AMB":  "amb_w_tds.amb_w_tds.doctype.batch_amb.batch_amb.BatchAMB"
}

# ========================================
#  FRONTEND JS INJECTIONS
# ========================================

doctype_js = {
    "Quotation": "amb_w_tds/amb_w_tds/doctype/batch_amb/quotation_sample_request.js",
    "Lead": "amb_w_tds/amb_w_tds/doctype/batch_amb/lead_sample_request.js",
    "Prospect": "amb_w_tds/amb_w_tds/doctype/batch_amb/prospect_sample_request.js",
    "Opportunity": "amb_w_tds/amb_w_tds/doctype/batch_amb/opportunity_sample_request.js",
    "Quotation AMB": "amb_w_tds/amb_w_tds/doctype/quotation_amb/quotation_amb.js",
    "Batch AMB": "amb_w_tds/amb_w_tds/doctype/batch_amb/batch_amb.js",
    "Work Order": "public/js/work_order_list.js", 
}

app_include_js = [
    "/assets/amb_w_tds/js/batch_widget.js",
    "/assets/amb_w_tds/js/work_order_list.js",
]

# ========================================
#  DOCUMENT EVENTS (Critical migration hooks)
# ========================================

doc_events = {

    # ---- BOM validation hooks (Phase 5)
    "BOM": {
        "on_submit": "amb_w_tds.bom_hooks.on_bom_submit",
        "on_update": "amb_w_tds.bom_hooks.on_bom_update",
    },

    # ---- stock trace / costing / batch migrations
    "Stock Entry": {
        "on_submit": [],
        "before_insert": [],
    },

    # ---- AMB Quotation + Sales Partner auto mapping + idempotency
    "Quotation AMB": {
        "before_insert": [],
        "before_save": [],
        "before_submit": [],
    },
}

# ========================================
#  SCHEDULER EVENTS (background consistency)
# ========================================

scheduler_events = {

    "hourly": [],

    "daily": [],

    "weekly": [
        # BOM Health Check - runs weekly (Phase 5)
        "amb_w_tds.scripts.scheduled_bom_health.run",
    ],
}

# ========================================
#  FIXTURES (sync mandatory custom fields)
# ========================================

fixtures = [

    # sales_partner + agent tracking required fields
    {
        "doctype": "Custom Field",
        "filters": [
            ["dt", "in", ["Quotation AMB", "Quotation", "Batch AMB"]],
        ]
    },

    # AMB workflows + automatic migration workflow states
    {
        "doctype": "Workflow",
        "filters": [
            ["name", "like", "AMB%"]
        ]
    },
]

# ========================================
# Webhooks and Portal Exposure (future)
# ========================================

default_mail_footer = """
    <div>
        Document generated by AMB Frappe Cloud System
    </div>
"""

# ================================================
# FRAPPE MONKEY PATCHES (BOM Tree Fix v16)
# ================================================

override_whitelisted_methods = {
	"frappe.desk.treeview.get_all_nodes": "amb_w_tds.amb_w_tds.api.bom_tree_fix.get_all_nodes_fixed"
}
