app_name = "amb_w_tds"
app_title = "AMB W TDS"
app_publisher = "AMB WELLNESS"
app_description = "AMB WELLNESS TDS + Migration + Quotation AMB system"
app_email = "support@amb-wellness.com"
app_license = "MIT"

# ========================================
#  MODULE LOAD + PATCH PREPARATION
# ========================================

# register custom DocTypes for override / extension
doctype_class = {
    "Batch AMB":  "amb_w_tds.amb_w_tds.doctype.batch_amb.batch_amb.BatchAMB"
}

# ========================================
#  FRONTEND JS INJECTIONS
# ========================================

doctype_js = {
    "Quotation AMB": "amb_w_tds/doctype/quotation_amb/quotation_amb.js",
    "Batch AMB": "amb_w_tds/doctype/batch_amb/batch_amb.js",
}

app_include_js = [
    "/assets/amb_w_tds/js/batch_widget.js"
]

# ========================================
#  DOCUMENT EVENTS (Critical migration hooks)
# ========================================

doc_events = {

    # ---- stock trace / costing / batch migrations
    "Stock Entry": {
        "on_submit": [
            # ""amb_w_tds.stock_entry_hooks.on_stock_entry_submit"",
            # ""amb_w_tds.raven.utils.on_stock_entry_submit""
        ],
        "before_insert": [
            # ""amb_w_tds.api.agent.pre_stock_entry_agent_validation""
        ],
    },

    # ---- AMB Quotation + Sales Partner auto mapping + idempotency
    "Quotation AMB": {

        # Idempotency + sales_partner assignment
        "before_insert": [
            # # ""amb_w_tds.api.agent.apply_agent_hooks"",
            # ""amb_w_tds.api.quotation_amb.idempotency_check""
        ],

        # logging + lineage trace + legacy ID mapping
        "before_save": [
            # ""amb_w_tds.api.agent.apply_activity_log"",
            # ""amb_w_tds.api.quotation_amb.audit_linkage""
        ],

        # enforce workflow + commission + agent
        "before_submit": [
            # ""amb_w_tds.api.quotation_amb.validate_commission"",
            # ""amb_w_tds.api.quotation_amb.ensure_sales_partner""
        ],
    },
}

# ========================================
#  SCHEDULER EVENTS (background consistency)
# ========================================
#
#scheduler_events = {
#
#    "hourly": [
#        # ""amb_w_tds.migration.resume_unfinished_migration"",
#        # ""amb_w_tds.api.agent.hourly_sync_agents""
#    ],
#
#    "daily": [
#        # ""amb_w_tds.api.audit.daily_quotation_amb_log_rotation"",
#        # ""amb_w_tds.migration.verify_pending_documents""
#    ],
#
#    "weekly": [
#        # ""amb_w_tds.agent.performance.weekly_commission_reconciliation"",
#        # ""amb_w_tds.migration.cleanup_stale_migration_state""
#    ],
#}
#
# ========================================
#  FIXTURES (sync mandatory custom fields)
# ========================================

fixtures = [

    # sales_partner + agent tracking required fields
    {
        "doctype": "Custom Field",
        "filters": [
            ["dt", "in", ["Quotation AMB", "Quotation", "Batch AMB"]],
        ]
    },

    # AMB workflows + automatic migration workflow states
    {
        "doctype": "Workflow",
        "filters": [
            ["name", "like", "AMB%"]
        ]
    },
]

# ========================================
# Webhooks and Portal Exposure (future)
# ========================================

default_mail_footer = """
    <div>
        Document generated by AMB Frappe Cloud System
    </div>
"""

# ================================================
# FRAPPE MONKEY PATCHES (BOM Tree Fix v16)
# ================================================

override_whitelisted_methods = {
	"frappe.desk.treeview.get_all_nodes": "amb_w_tds.amb_w_tds.api.bom_tree_fix.get_all_nodes_fixed"
}

